# Site
name: 'Korporate'
description: 'Korporate from Infozy is the Digital News Website for Business.'
group: "Infozy"
group-url: "https://infozy.tk"
baseurl: ''
disqus: 'read-write-tech'
email: 'tksudharshan@infozy.tk'
siteurl: 'https://korporate.infozy.tk'
newsletter: 'tksudharshan@infozy.tk'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    shan:
      name: 'Sudharshan TK'
      site: https://shan.infozy.tk
      avatar: 'https://s.gravatar.com/avatar/c0ec2e063895760baa493c36d2d28387?s=400'
      bio: "CA Finalist | Android App Developer | Web Developer | Android Debugger<br />Working in Ford Rhodes Parks
  & Co LLP as a Article Assistant."
      email: tksudharshan@infozy.tk

# Image Configurations

cdn: https://cdn.statically.io/img/
image: educate.infozy.tk/assets/images/
height_thumbnail: 580
width_thumbnail: 920
height_post: 1080
width_post: 1920
width_home_featured_thumbnail: 720
height_home_featured_thumbnail: 960
auto_webp_conversion: true


# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: 'Sudharshan TK'
      avatar: https://s.gravatar.com/avatar/a444de646212803b37630a7a91e5bc22?s=500
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
