backend:
  name: git-gateway
  branch: master
media_folder: "assets/images/posts/"
logo_url: https://businet.infozy.tk/assets/images/logo.png
site_url: https://businet.infozy.tk
display_url: https://businet.infozy.tk
publish_mode: editorial_workflow
collections:
  - label: "Posts"
    name: "posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{title}}"
    extension: "md"
    fields:
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss +0530"
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Comments"
        name: "comments"
        widget: "hidden"
        default: true
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        hint: "This will be used across the pages and for search engines."
        widget: "string"
      - label: "Category"
        name: "categories"
        widget: "list"
        hint: "Separate with commas. These will also be used as keywords for search engines."
      - label: "Tags"
        name: "tags"
        hint: "Separate with commas. These will also be used as keywords for search engines."
        widget: "list"
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        displayFields: [display_name]
        searchFields: [display_name]
        valueField: "name"
      - label: "Featured Image"
        name: "image"
        widget: "string"
        required: false
        hint: "Give Source Image Url or Upload the Image !Important - Select only One Option"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - label: "Pages"
    name: "_pages"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    extension: "md"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "page"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Permalink"
        name: "permalink"
        widget: "hidden"
        default: "/{{slug}}/"
      - label: "Description"
        name: "description"
        hint: "This will be used as description for search engines."
        widget: "string"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"